### ISSUE TITLE
补充配置细节描述

### ISSUE THREAD

**Issue by fsy2001** [OpenTreeHole/auth_next#1]
按照README中的说明无法运行程序，需要补充运行细节，包括（但不限于）：
- 网关安装及配置插件
- 环境变量设置
- identifier salt, provision key

**Comment by JingYiJun** [comment]
本地测试不用配置网关了=了，identifier salt 有默认值，provision key不用配。只要按照 README 配置环境变量 STANDALONE = TRUE 就能跑
