### ISSUE TITLE
[Feature Request] 添加账号注销页面

### ISSUE THREAD

**Issue by w568w** [OpenTreeHole/auth_next#10]
Google play 现在要求必须提供删除账号的 URL，不可以是电子邮箱地址。

本 issue 阻塞了 <https://github.com/DanXi-Dev/DanXi/issues/263>，继而阻塞 1.4.0 Milestone。

**Comment by JingYiJun** [comment]
已经有账号注销的API了

DELETE /api/users/me 
和
DELETE /api/users/{id}
